version: '3'

services:
  create:
    build: .
    environment:
      TF_VAR_APPLICATION_NAME: ${APPLICATION_NAME}
      TF_VAR_AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      TF_VAR_AWS_REGION: ${AWS_REGION}
      TF_VAR_AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./store:/app
